#%RAML 1.0 NamedExample
value:
  - id: 3
    user_id: 6
    is_driving:
      id: 4
      company_id: HHT-01
  
  - id: 4
    user_id: 7
    is_driving:
      id: 5
      company_id: Horch-01
  
  - id: 5
    user_id: 6
  
  - id: 6
    user_id: 7